# Generated by Django 5.0.4 on 2024-05-01 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_alter_wallet_left_date_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='money.wallet'),
        ),
    ]
