# Generated by Django 5.0.4 on 2024-05-02 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_alter_purchase_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='daily',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='left_date',
            field=models.DateField(default=datetime.date(2024, 5, 9)),
        ),
    ]
