# Generated by Django 5.0.4 on 2024-05-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_wallet_daily_alter_wallet_left_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='daily',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
