# Generated by Django 5.0.4 on 2024-05-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0005_alter_wallet_daily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='daily',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
