# Generated by Django 5.0.4 on 2024-05-03 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0006_alter_wallet_daily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='left_date',
            field=models.DateField(default=datetime.date(2024, 5, 10)),
        ),
    ]
