# Generated by Django 5.0.4 on 2024-05-05 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0007_alter_wallet_left_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='left_date',
            field=models.DateField(default=datetime.date(2024, 5, 12)),
        ),
    ]
