# Generated by Django 5.0.4 on 2024-05-09 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0008_alter_wallet_left_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date']},
        ),
        migrations.AddField(
            model_name='wallet',
            name='avaiable_today',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='left_date',
            field=models.DateField(default=datetime.date(2024, 5, 16)),
        ),
    ]
