# Generated by Django 5.0.4 on 2024-05-11 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0010_rename_avaiable_today_wallet_available_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='left_date',
            field=models.DateField(default=datetime.date(2024, 5, 18)),
        ),
    ]
